version: "3.9"
services:
  postgres:
    image: postgres:15-bookworm
    volumes:
      - /opt/databases/prod/status-page/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gatus
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    networks:
      - web
      - db

  gatus:
    image: twinproduction/gatus:stable
    restart: always
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gatus
    volumes:
      - ./config:/config
    networks:
      - web
      - db
    depends_on:
      - postgres

networks:
  web:
    driver: bridge
  db:
