storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

endpoints:
  - name: alix
    group: servers
    url: "https://alix.711666.xyz/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: bworm
    group: servers
    url: "https://bworm.hanz.lol/"
    interval: 5m
    conditions:
      - "[STATUS] == 526"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  
  - name: code
    group: servers
    url: "https://code.hanz.lol/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  
  - name: demi
    group: servers
    url: "https://demi.hanz.lol"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  
  - name: east
    group: servers
    url: "https://east.hanz.lol/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
